version: "3.10"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./uploads:/app/uploads   

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
