name: Backend CI/CD Pipeline

on:
  workflow_dispatch:


jobs:
  build-and-push-to-ECR:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17 for Maven
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # Step 3: Build backend with Maven
    - name: Build backend JAR
      working-directory: ./backend
      run: mvn clean package -DskipTests

    # Step 4: Run unit tests 
    - name: Run unit tests
      working-directory: ./backend
      run: mvn test

    # Step 5: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 6: Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 7: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t backend-image:${{ github.sha }} ./backend

    # Step 8: Tag Docker image for ECR
    - name: Tag Docker image
      run: |
        docker tag backend-image:${{ github.sha }} ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

    # Step 9: Push Docker image to ECR
    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
