name: Backend CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-push-to-ECR:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17 for Maven
    - name: Set up JDK 17
      uses: actions/setup-java@3
      with:
        distribution: temurin
        java-version: 17

    # Step 3: Build backend with Maven
    - name: Build backend JAR
      working-directory: ./backend
      run: mvn clean package -DskipTests

    # Step 4: Run unit tests
    - name: Run unit tests
      working-directory: ./backend
      run: mvn test

    # Step 5: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    # Step 6: Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 7: Build Docker image
    - name: Build Docker image
      run: docker build -t inventory-app ./backend

    # Step 8: Tag Docker image for ECR 
    - name: Tag Docker image for ECR (latest)
      run: docker tag inventory-app ${{ secrets.ECR_REPOSITORY }}:latest

    # Step 9: Push Docker image to Amazon ECR 
    - name: Push Docker image to Amazon ECR (latest)
      run: docker push ${{ secrets.ECR_REPOSITORY }}:latest


  deploy-to-ECS:
    needs: build-and-push-to-ECR
    runs-on: ubuntu-latest
    steps:
    # Step 1: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 2: Update ECS service to use latest image
    - name: Update ECS service to use latest image
      run: |
        aws ecs update-service \
          --cluster inventory-cluster \
          --service inventory-backend-service \
          --force-new-deployment \
          --region ${{ secrets.AWS_REGION }}

    
